# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27f0496fc8014fd57658862831df3a7b82ea7ad565626707bbc64df560e695b3a482755f289e1670d534474faeb1a28065d45ef969e46cbc8d72c294baf38352

test:
  secret_key_base: 18f48718ec7c2f82af5d06c7ee85d0d9ae817bb7521ddc8cdfef4d927559b21e6003b7ade135382028ac71134910cfaeb839f1c87f2df87b0a324336c08ccc4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
